aquasecurity/vuln-list-update

- README.md
- alpine/alpine.go
- debian/debian.go
- git/git.go
- main.go
- nvd/nvd.go
- oval/debian/debian.go
- push.sh
- redhat/redhat.go
- ubuntu/ubuntu.go
> Transfer repositoriy

- git/git.go
- main.go
- utils/utils.go
Changed to be available in other repositories.
Since rev-parse returns an error when there is no commit, it is changed to rev-list.
> available in other repositories

- debian/debian.go
- debian/debian_test.go
- debian/testdata/fixtures/debian.json
- debian/testdata/fixtures/invalid.json
- debian/testdata/goldens/debian/prototypejs/CVE-2007-2383.json.golden
- debian/testdata/goldens/debian/prototypejs/CVE-2008-7220.json.golden
- debian/testdata/goldens/debian/python-scipy/CVE-2013-4251.json.golden
- main.go
- utils/utils.go
Close https://github.com/aquasecurity/vuln-list-update/issues/10
> fix(debian): remove rejected vulnerabilities

- .travis.yml
- CONTRIBUTING.md
> add contribution guidelines

- .travis.yml
Fetch Red Hat OVAL on CronJob
Related: https://github.com/aquasecurity/vuln-list-update/pull/19
> chore(ci): add Red Hat OVAL

- amazon/amazon.go
- amazon/amazon_test.go
Amazon added ALAS-2020-1383, but it was removed now.
https://alas.aws.amazon.com/alas2.html
This sometimes seems to happen. To handle it, we should remove the directory once and add all files to the directory again.
> fix(amazon): handle removed ALAS

- git/git.go
In the repository which is cloned with `--depth 1` option, `git branch --remote` doesn't work. Before that, we need the following commands to fetch remote branches.
```
$ git config "remote.origin.fetch", "+refs/heads/*:refs/remotes/origin/*
$ git fetch --all
```
This bug was introduced by https://github.com/aquasecurity/vuln-list-update/pull/26.
> fix(git): fetch all branches

- nvd/nvd.go
Signed-off-by: Simarpreet Singh <simar@linux.com>
> nvd: bump to use 1.1 schema for baseMetricsV3

- alpine/alpine.go
- alpine/alpine_test.go
- alpine/testdata/aports/main/libssh2/APKBUILD
- alpine/testdata/goldens/main/libssh2/CVE-2019-13115.json.golden
- alpine/testdata/goldens/main/libssh2/CVE-2019-17498.json.golden
vuln-list-update expects "secfixes" as a comment in APKBUILD, but it rarely has "security fixes".
> fix(alpine): handle security fixes

- main.go
Signed-off-by: Simarpreet Singh <simar@linux.com>
> cwe: Add a commit message to updates

- ubuntu/testdata/empty_status_upstream
- ubuntu/testdata/include_pending
- ubuntu/testdata/line_break_between_patches
- ubuntu/testdata/more_than_one_package_patches
- ubuntu/testdata/multiple_upstreams
- ubuntu/testdata/no_space_before_status
- ubuntu/testdata/patches_with_status
- ubuntu/ubuntu.go
- ubuntu/ubuntu_test.go
[Issue](https://github.com/aquasecurity/vuln-list-update/issues/41)
> Updated logic to parse patches in ubuntu CVE file

- README.md
Remove travis info from `README.md`
> remove travis info

- .github/workflows/update.yml
> Add workflow_dispatch for manual trigger

- git/git.go
- main.go
- ubuntu/ubuntu.go
If the process fails in the middle, cruft will be left behind.
> feat: clean repository at the end

- .github/workflows/update.yml
Even if one of the steps fails, the remaining steps should be continued.
https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#always
Only failure steps would be red.
> chore(actions): run steps always

- README.md
> chore: update Apache icon in Readme

- .github/workflows/update.yml
https://github.com/aquasecurity/vuln-list-update/actions/runs/939310756/workflow
> chore(cron): fix a broken yaml

- ghsa/ghsa.go
Added golang support in ghsa source
> Added golang support in ghsa source

- debian/tracker/annotation.go
- debian/tracker/debian_test.go
- debian/tracker/testdata/happy/data/CVE/list
> fix(debian): handle severity properly

- rocky/rocky.go
- rocky/testdata/golden/2021/RLSA-2021:2575.json
- rocky/testdata/golden/2021/RLSA-2021:3057.json
There is information about the source package in updateinfo, so add it.
> feat(rocky): add source package info

- rocky/rocky.go
- rocky/rocky_test.go
- rocky/types.go
Rocky database has been split into 2 urls:
- https://dl.rockylinux.org/vault/rocky
- https://download.rockylinux.org/pub/rocky
Added parsing of both links.
> fix(rocky): added 2 urls parse

- amazon/amazon_test.go
fix ambiguity in `bad gzip data response` test for `amazon linux`.
> test(amazon): fix test error

- alma/alma.go
add AlmaLinux 9.
advisory URL: https://errata.almalinux.org/9/errata.json
> feat(alma): add AlmaLinux 9

- glad/glad.go
Removed duplicate nuget in supportedTypes and sorted.
> chore(glad): remove duplicate nuget in supportedTypes

- ghsa/ghsa.go
add data from GHSA for Rust ecosystem: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Arust
> feat: add Rust ecosystem from GitHub Advisory Database

- ghsa/ghsa.go
Add `pub` ecosystem for `Dart`
> feat(ghsa): add pub ecosystem

- .github/workflows/update.yml
- README.md
- chainguard/chainguard.go
- chainguard/chainguard_test.go
- chainguard/testdata/golden/binutils.json
- chainguard/testdata/security.json
- main.go
Adds support for ingesting Chainguard's distro secdb for https://github.com/aquasecurity/trivy/issues/3630
> feat(chainguard): add support for Chainguard distro

- .github/workflows/update.yml
vuln-list works now. This PR reverts commit 66b50df09145a936e4edfe4484d1a8c86a3f9597.
> Revert "chore: fall back into vuln-list-reserve (#229)"

- scripts/create_pr.sh
add sleep between k8s vuln prs
> chore: add sleep between k8s vuln prs

- amazon/amazon.go
- go.mod
- go.sum
- nvd/nvd.go
- oracle/oval/oval.go
- utils/utils.go
The project used two versions of `github.com/cheggaaa/pb`. Replaced v1 with v3.
> chore(deps): use github.com/cheggaaa/pb/v3

- nvd/nvd_test.go
- nvd/testdata/fixtures/respPage2.json
- nvd/testdata/golden/api/2024/CVE-2024-5732.json
- nvd/types.go
CVSS V4.0 Metrics is now included in the NVD API response.
> feat(nvd): add cvssMetricV40

- redhat/securitydataapi/redhat.go
fixes https://github.com/aquasecurity/vuln-list-redhat/issues/1
> feat(redhat/securitydataapi): clean fetch directory before fetch

- .github/workflows/debian.yml
- .github/workflows/nvd.yml
- .github/workflows/redhat.yml
- .github/workflows/update.yml
Add `teams` notifications for `update` workflows:
- update (vuln-list)
- nvd (vuln-list-nvd)
- RedHat (vuln-list-redhat)
- Debian (vuln-list-debian)
> ci: add teams notifications for update workflows

- alma/alma.go
Fixes https://github.com/aquasecurity/trivy/issues/9189
This pr updates vul support for almalinux 10
Screenshot showing trivy-db contains advisories for almalinux 10 version
> feat(alma): add AlmaLinux 10 support
