aquasecurity/vuln-list-update

go.mod, go.sum, redhat/redhat.go, redhat/testdata/CVE-2009-2694.json, redhat/testdata/CVE-2019-7614.json, redhat/types.go, redhat/types_test.go
Red Hat returns string or object as mitigation.
https://github.com/aquasecurity/trivy/issues/169
=> Support the case when Red Hat returns the different type

.travis.yml
ALAS (Amazon Linux AMI Security Advisory) should be fetched daily on CronJob of Travis CI
=> chore(amazon): fetch ALAS by cron

oval/redhat/redhat.go
afero.AppFs is used elsewhere.
=> fix(redhat-oval): replace os.MkdirAll with AppFs.MkdirAll

git/git.go
Use shallow clone can reduce the download size by 80% when getting vuln-list repo
=> Use shallow clone

cvrf/suse/suse.go, cvrf/suse/suse_test.go, cvrf/suse/testdata/cvrf-list.html, cvrf/suse/testdata/cvrf-opensuse-su-2016-0874-1.xml, cvrf/suse/testdata/golden/openSUSE-SU-2016-0874-1.json
Fix the following issue
https://github.com/aquasecurity/vuln-list-update/runs/1337105587?check_suite_focus=true
SUSE recently added invalid UTF-8 characters to their CVRF. I'm sure it is a bug, but `vuln-list-update` should be able to handle it. This PR removes all invalid characters with `strings.ToValidUTF8`.
=> fix(cvrf/suse): handle invalid UTF-8 characters

.github/workflows/update.yml
Ref https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> chore(actions): deprecate set-env

.github/workflows/update.yml, photon/photon.go
Photon has migrated all of the repositories from Bintray to Packages.vmware.com.
This specific repository can be accessed from https://packages.vmware.com/photon/photon_cve_metadata/photon_versions.json
=> fix(photon): migrate the repository

oval/redhat/redhat.go
Some platforms such as EUS don't provide `-including-unpatched` files. They should also be included in vuln-list.
=> feat(redhat): add all OVAL files

ubuntu/ubuntu.go
resolves #76 and #77
- also `git://git.launchpad.net/ubuntu-cve-tracker` to Ubuntu CVE tracker repo URL
- remove `vuln-list/ubuntu` before updating
~tested with workflow [here](https://github.com/ronaudinho/vuln-list-update/runs/2083195047?check_suite_focus=true), some results:~
- ~[CVE-2019-12378](https://github.com/ronaudinho/vuln-list/blob/dba362842c7eac3a0c54826b192e11130aa62a75/ubuntu/2019/CVE-2019-12378.json#L206)~
- ~[CVE-2019-12379](https://github.com/ronaudinho/vuln-list/blob/dba362842c7eac3a0c54826b192e11130aa62a75/ubuntu/2019/CVE-2019-12379.json#L206)~
tested with workflow [here](https://github.com/ronaudinho/vuln-list-update/runs/2083878438?check_suite_focus=true), both are [gone in latest vuln-list](https://github.com/ronaudinho/vuln-list/commit/2d0860d6b76d76a9f2ea24c35fdc40a …
=> ubuntu: remove vuln-dir before update

ubuntu/ubuntu.go
resolves #76 and #77. failing fetch into existing git dir causes the next clone/pull attempt to fail, this adds removing said dir before retrying clone/pull.
=> ubuntu: remove dir if clone/pull fails halfway

redhat/oval/redhat.go
[Issue](https://github.com/aquasecurity/vuln-list-update/runs/2680385211?check_suite_focus=true)
=> fix(redhat): skip empty oval file

.github/workflows/update.yml
The year 2022 has been added to the Red Hat Security Data API part of update.yml.
```console
$ VULN_LIST_DEBUG=1  ./vuln-list-update -target redhat -years 2022
2022/01/07 14:10:18 target repository is aquasecurity/vuln-list
2022/01/07 14:10:18 Skip git pull
2022/01/07 14:10:18 Fetching RedHat: year 2022
2022/01/07 14:10:18 page 1
2022/01/07 14:10:19 page 2
7 / 7 [============================================================] 100.00% 0s
```
=> chore: add Red Hat Security Data API 2022

rocky/rocky.go, rocky/rocky_test.go, rocky/testdata/fixtures/no_updateinfo_field/repomd.xml
fixes https://github.com/aquasecurity/vuln-list-update/runs/4915644952?check_suite_focus=true
If the repository is extras and there is no updateinfo field in repomd.xml, it will output a log and skip it.
```console
$ VULN_LIST_DEBUG=1 ./vuln-list-update -target rocky
2022/01/24 20:22:29 target repository is aquasecurity/vuln-list
2022/01/24 20:22:29 Skip git pull
2022/01/24 20:22:29 Fetching Rocky Linux 8 BaseOS x86_64 data...
2022/01/24 20:22:29 Remove Rocky Linux 8 BaseOS x86_64 directory /home/mainek00n/.cache/vuln-list-update/vuln-list/rocky/8/BaseOS/x86_64
2022/01/24 20:22:30 Write Errata for Rocky Linux 8 BaseOS x86_64 2021
9 / 9 [----------------------------------------------------------] 100.00% ? p/s
2022/01/24 20:22:30 Write Errata for Rocky Linux 8 BaseOS x86_64 2022
1 / 1 …
```
=> fix(rocky): skip when repository is extras and there is no updateinfo in repomd.xml

glad/glad.go, main.go
By default we are building `vuln-list` for `glad` by using https://gitlab.com/gitlab-org/advisories-community database, we would like to allow customizing this, so users can build their own databases based on https://gitlab.com/gitlab-org/advisories-community. 
Example:
```
vuln-list-update -target glad -target-uri "https://gitlab.com/mparuszewski/custom-advisories-database" -target-branch "main"
```
Both parameters `-target-uri` and `-target-branch` can be easily reused for other targets (ie. alpine, mariner, etc.).
=> feat(glad): add ability to set custom repository uri

ghsa/ghsa.go, ghsa/ghsa_test.go
GitHub GraphQL API may return error and one of nodes is empty
Added skip "bad" nodes.
See more: github/advisory-database#221
=> fix(ghsa): added nil check for received nodes

glad/glad.go, glad/glad_test.go, glad/testdata/golden/glad/go/github.com/docker/distribution/GHSA-qq97-vm5h-rrhg.json, glad/testdata/happy/go/github.com/docker/distribution/GMS-2022-20.yml, glad/types.go
GitLab advisory database contains GMS identifiers, and we should handle them.
=> feat(glad): add parse for identifiers field

ghsa/ghsa.go
Erlang has been added to the GitHub Security Advisory.
https://github.blog/changelog/2022-06-27-github-advisory-database-now-includes-erlang-and-elixir-advisories/
At the time I checked, it is not reflected in the docs.
https://docs.github.com/en/graphql/reference/enums#securityadvisoryecosystem
However, it seems that `ERLANG` is added to the schema.
https://github.com/octokit/graphql-schema/blob/34d7f06ea7d0e35c43048c1e82e3c654be0220b7/schema.d.ts#L20727-L20728
=> feat(ghsa): add Erlang/Elixir advisory

oracle/oval/testdata/golden/ELSA-2007-0057.json, oracle/oval/testdata/golden/ELSA-2008-0110.json, oracle/oval/testdata/golden/ELSA-2009-1203.json, oracle/oval/testdata/golden/ELSA-2010-0809.json, oracle/oval/testdata/golden/ELSA-2011-1268.json, oracle/oval/testdata/golden/ELSA-2012-1261.json, oracle/oval/testdata/golden/ELSA-2013-1732.json, oracle/oval/testdata/golden/ELSA-2014-2010.json, oracle/oval/testdata/golden/ELSA-2015-2561.json, oracle/oval/testdata/golden/ELSA-2016-3646.json, oracle/oval/testdata/golden/ELSA-2017-3516.json, oracle/oval/testdata/golden/ELSA-2018-1196-1.json, oracle/oval/testdata/golden/ELSA-2018-3410.json, oracle/oval/testdata/golden/ELSA-2019-4820.json, oracle/oval/testdata/golden/ELSA-2019-4821.json, oracle/oval/types.go, oracle/oval/types_test.go
Oracle-oval release date not capturing. 
Added Issued in the types. this will pull the release date.
=> fix(oracle-oval): added release date.

glad/glad.go, glad/glad_test.go, glad/testdata/golden/happy/glad/maven/org.springframework.boot/spring-boot-starter-web/CVE-2022-22965.json, glad/testdata/happy/maven/org.springframework.boot/spring-boot-starter-web/GMS-2022-560.yml
GitLab can use `GSM-xxx`  as `identifier`.
First we need  find `CVE-ID`. If `CVE-ID` is not found, then try to find `GHSA-ID`.
e.g. - https://gitlab.com/gitlab-org/security-products/gemnasium-db/-/blob/master/maven/org.springframework.boot/spring-boot-starter-web/GMS-2022-560.yml
- https://github.com/aquasecurity/trivy/issues/4176
=> fix(glad): select CVE-ID before GHSA-ID

.github/workflows/squash.yml
Now `vuln-list` is a large repository that contains about 20'000 commits and 117'000'000 objects.
the total size is about 24Gb.
Github has a limit for repositories - 5Gb.
so we have to squash vuln-list - clone the shallow repository (the last 100 commits), squash and push.
=> ci: squash `vuln-list` using git-filter-repo

.github/workflows/debian.yml, .github/workflows/update.yml, debian/tracker/debian.go, debian/tracker/debian_test.go, main.go
The updates and motivations of this PR are the same as https://github.com/aquasecurity/vuln-list-update/pull/217.
In addition, this PR splits source JSON files, which are more than 50MB. Large files are not for git.
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github
- https://github.com/knqyf263/vuln-list-update/actions/runs/5375306167
- https://github.com/knqyf263/vuln-list-debian/tree/main
=> BREAKING CHANGE: extract Debian security advisories to separate repo

debian/tracker/annotation.go, debian/tracker/debian.go, debian/tracker/debian_test.go, debian/tracker/list.go
Line numbers are frequently updated, and it increases the repository size dramatically.
https://github.com/aquasecurity/vuln-list-debian/commit/2b34d21590746aa7314fde530fe70478151a4156
Although vuln-list-debian should keep the original content as much ass possible, the repository size is critical. This PR drops line numbers as it is not used in trivy-db.
=> fix(debian): remove line

.github/workflows/update.yml
vuln-list is down now, and it is failing to build trivy-db. We need a temporal solution until it will be back.
=> chore: fall back into vuln-list-reserve

ghsa/ghsa.go, ghsa/ghsa_test.go, ghsa/testdata/swift/github.com/grpc/grpc-swift/GHSA-r6ww-5963-7r95.json
Add [swift](https://github.com/advisories?query=type%3Areviewed+ecosystem%3Aswift) support.
=> feat(ghsa): add swift support

.github/workflows/nvd.yml, .github/workflows/update.yml, nvd/nvd.go
The updates and motivations of this PR are the same as https://github.com/aquasecurity/vuln-list-update/pull/217.
- https://github.com/DmitriyLewen/vuln-list-update/actions/runs/5666605153
- https://github.com/dmitriylewen/vuln-list-nvd/tree/main
=> BREAKING CHANGE: extract NVD advisories to separate repo

scripts/create_pr.sh
increase `gh list pr` page limit when query for open PRs
fix this [error](https://github.com/aquasecurity/vuln-list-update/actions/runs/6368520330/job/17287946530) 
I have increased `limit to 50` (enough for now , default limit is 30) should be ok for now I assume it will happen only for initial db creation
=> chore: increase k8s open prs limit

debian/tracker/debian.go, debian/tracker/debian_test.go, debian/tracker/testdata/happy/data/CVE/list
There are multiple entries called `CVE-yyyy-XXXX` in `CVE/list`.
ref. https://salsa.debian.org/search?search=XXXX&nav_source=navbar&project_id=555&group_id=2102&search_code=true&repository_ref=master
However, the current vuln-list-update does not consider them, and only one is saved as `vuln-list-debian/tracker/CVE/yyyy/CVE-yyyy-XXXX.json`.
ref. https://github.com/search?q=repo%3Aaquasecurity%2Fvuln-list-debian%20XXXX&type=code
If you look at these entries on the Debian Security Tracker on the web, they will be converted to entries called TEMP.
ref. https://security-tracker.debian.org/tracker/data/fake-names
The conversion method is as follows.
https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/50ca55fb66ec7592f9bc1053a11dbf0bd50ee425/lib/python/bugs.py#L402-408
This …
=> feat(debian/tracker): add TEMP entry instead of CVE-yyyy-XXXX

scripts/update.sh
If the update script fails midway through, the state of the directory remains intact and is accidentally committed in another step. Then, it will fail to build trivy-db. Failure of vuln-list-update is expected and must not affect trivy-db builds. The changes should be reverted in case of an error.
=> fix: revert changes on error

scripts/update.sh
https://github.com/aquasecurity/vuln-list-update/pull/272 accidentally reverts vuln-list-update, not vuln-list.
=> fix: reset vuln-list

mariner/mariner.go
Microsoft changed the repository name from CBL-MarinerVulnerabilityData to AzureLinuxVulnerabilityData, and it broke our pipeline.
https://github.com/microsoft/AzureLinuxVulnerabilityData
=> fix(mariner): replace CBL-MarinerVulnerabilityData with AzureLinuxVulnerabilityData

mariner/testdata/golden/azure/3.0/definitions/2023/52881-2.json, mariner/testdata/golden/azure/3.0/definitions/2024/42064-1.json, mariner/testdata/golden/azure/3.0/objects/objects.json, mariner/testdata/golden/azure/3.0/states/states.json, mariner/testdata/golden/azure/3.0/tests/tests.json, mariner/testdata/golden/mariner/1.0/definitions/2008/3173.json, mariner/testdata/golden/mariner/1.0/definitions/2018/4209.json, mariner/testdata/golden/mariner/1.0/definitions/2021/4820.json, mariner/testdata/golden/mariner/2.0/definitions/2014/6933.json, mariner/testdata/golden/mariner/2.0/definitions/2021/7412.json, mariner/testdata/golden/mariner/2.0/definitions/2022/7700.json, mariner/testdata/golden/mariner/2.0/definitions/2023/31872-1.json, mariner/testdata/golden/mariner/2.0/definitions/2023/31880-1.json, mariner/testdata/happy/azurelinux-3.0-oval.xml, mariner/types.go
We need to save all `criterion` for `definition`.
e.g. :
```xml
<criteria operator="AND">
<criterion comment="Package golang is earlier than 1.20.7-1, affected by CVE-2023-29409" test_ref="oval:com.microsoft.azurelinux:tst:52881000"/>
<criterion comment="Package golang is greater than 0.0.0, affected by CVE-2023-29409" test_ref="oval:com.microsoft.azurelinux:tst:52881003"/>
</criteria>
```
Test GH actions run - https://github.com/DmitriyLewen/vuln-list-update/actions/runs/11832818656/job/32970285972
These changes affect only `definitions/<year>/*.json` files.
Before(https://github.com/aquasecurity/vuln-list/blob/b9a2b63e2a5e1c1db6dd31af38460eb2b666dcd2/azure/3.0/definitions/2023/52881-2.json#L23-L26):
```json
"Criteria": {
"Operator": "AND",
"Criterion": {
"Comment": "Package golang is …
```
=> fix(azure): support of multiple `criterion`

redhat/csaf/vex.go, redhat/oval/redhat.go
> repository-to-cpe.json 	This file will be moved to the “/meta/v1” path. 	November 1, 2023* 
>
> * Important note: Since this file is intensively used, a copy of this file will remain in the "/data/metrics/" path until the end of 2024 to allow smooth migration.
https://www.redhat.com/en/blog/future-red-hat-security-data
> Note: Security data (CSAF, OVAL, SBOM, and other files) published by Red Hat Product Security was previously served from two locations:
>
>    https://access.redhat.com/security/data/*
>   https://www.redhat.com/security/data/*
>
> A new domain was recently created the scope of which (for the time being) is to serve this same data:
>
>    https://security.access.redhat.com/data/*
https://access.redhat.com/security/data
=> chore(redhat): update url

nvd/nvd.go, nvd/nvd_test.go, nvd/testdata/fixtures/emptyResp.json
I found cases when `NVD` returns empty `vulnerabilities`:
- https://github.com/aquasecurity/vuln-list-update/actions/runs/11952931174/job/33319733712
- https://github.com/aquasecurity/vuln-list-update/actions/runs/11959096497/job/33340124175
For these runs we updated `last_update` time:
- https://github.com/aquasecurity/vuln-list-nvd/commit/30043e9c29cf127adf642f24d63d87b6791130e4
- https://github.com/aquasecurity/vuln-list-nvd/commit/f6c474ff1e0f0385d4e4fdeac15a2ccca6e98894
I think it was a bug in NVD because now I see vulnerabilities:
```bash
curl -s 'https://services.nvd.nist.gov/rest/json/cves/2.0/?lastModStartDate=2024-11-21T12:12:38&lastModEndDate=2024-11-21T18:09:55' | jq '.vulnerabilities | length'
208
```
But in any case, we lost changes in CVE from these intervals …
=> fix(nvd): don't update last_update if it returned no records

redhat/securitydataapi/redhat.go
We got 403 error for RedHat advisories - https://github.com/aquasecurity/vuln-list-update/actions/runs/15430613251/job/43427586168
It looks like RedHat migrated to new base URL: `https://access.redhat.com/hydra/rest/securitydata`
See https://docs.redhat.com/en/documentation/red_hat_security_data_api/1.0/html/red_hat_security_data_api/overview
Test run with new BaseURL - https://github.com/DmitriyLewen/vuln-list-update/actions/runs/15434557664/job/43438396158#step:8:10
=> fix(redhat): change base URL for data API

ubuntu/testdata/blank_lines_in_description, ubuntu/testdata/notes_with_continuation_lines, ubuntu/ubuntu.go, ubuntu/ubuntu_test.go
This PR fixes parsing issues in ubuntu-cve-tracker where blank lines within multi-line fields caused data loss:
The ubuntu.go parser stopped processing multi-line fields (Description, Notes, etc.) when encountering blank lines, causing:
- [CVE-2017-5192](https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2017-5192#n11): Description truncated after blank line
- [CVE-2017-9779](https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2017-9779#n13): Notes parsing incomplete
- Similar issues in other multi-line fields
- [CVE-2017-5192](https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2017-5192#n11) now parses complete description (506 characters)
- All existing tests continue to pass
- New test cases cover blank line scenarios
=> fix(ubuntu): handle blank lines in ubuntu CVE parsing

nvd/nvd.go, nvd/nvd_test.go
NVD requires `offset-from-UTC` for time parameters. 
Use `time.RFC3339` format.
More info in #361
test run - https://github.com/DmitriyLewen/vuln-list-update/actions/runs/16514505804/job/46702716862
- Close #361
=> fix(nvd): add `offset-from-UTC` suffix

ubuntu/testdata/tags_field_parsing, ubuntu/ubuntu.go, ubuntu/ubuntu_test.go
This PR adds support for parsing the Tags field in ubuntu-cve-tracker data with proper space separation:
- Add `Tags []string` field to Vulnerability struct
- Implement Tags parsing logic using `strings.Fields()` for space separation
- Add comprehensive test case using [CVE-2022-22965](https://git.launchpad.net/ubuntu-cve-tracker/tree/active/CVE-2022-22965) data
- Support both single and multiple space-separated tags
Before: Tags field not supported, CISA KEV information lost
After: Tags field properly captured in generated JSON
```bash
$ jq '.Tags' vuln-list/ubuntu/2022/CVE-2022-22965.json
[
"cisa-kev",
"epss-prioritized"
]
```
The Tags field is now successfully parsed and included in the generated JSON output.
=> feat: add Tags field support for ubuntu CVE parsing

.github/workflows/redhat.yml
The size of vuln-list-redhat is more than 20 GB:
```
➜ du -sh ./vuln-list-redhat        
20G	./vuln-list-redhat
```
And we can’t clone this repo — see [GitHub Actions log](https://github.com/aquasecurity/vuln-list-update/actions/runs/18271712405/job/52015219867).
We need to use `remove-unwanted-software` to free up more disk space.
Test run - https://github.com/DmitriyLewen/vuln-list-update/actions/runs/18272869389/job/52018453626
=> ci(redhat): add `remove-unwanted-software`
